name: .NET Core

on: [push]

jobs:
  build:

    name: Build for platform ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [linux-x64, win-x64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build StatementParser/StatementParser.sln --configuration Release
    - name: Publish with dotnet
      run: dotnet publish -r ${{matrix.platform}} --configuration Release --self-contained true StatementParser/StatementParser.sln
    - name: Publish StatementParserCLI artifacts to GitHub
      uses: actions/upload-artifact@v1
      with:
        name: StatementParserCLI_${{matrix.platform}}
        path: StatementParser/StatementParserCLI/bin/Release/netcoreapp3.0/${{matrix.platform}}/publish
    - name: Publish TaxReporterCLI artifacts to GitHub
      uses: actions/upload-artifact@v1
      with:
        name: TaxReporterCLI_${{matrix.platform}}
        path: StatementParser/TaxReporterCLI/bin/Release/netcoreapp3.0/${{matrix.platform}}/publish
